version: '3'

services:

  ## MongoDB
  mongo:
    image: mongo
    command: mongod --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=32000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 100
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - $mongo_dir_0:/data/db:delegated

  ## Redis
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "$redis_dir:/data:delegated"
    entrypoint: redis-server --maxmemory 25000000000 --maxmemory-policy allkeys-random