# by TheTechromancer

version: '3'

services:

  ## MongoDB main DB
#  mongo_main:
#    image: mongo
#    # feel free to change hard-coded memory limits to match your hardware requirements
#    command: mongod --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=32000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 20
#    ports:
#      - "127.0.0.1:27017:27017"
#    volumes:
#      - $mongo_main_dir:/data/db:delegated
#    ulimits:
#      nproc: 65535
#      nofile:
#        soft: 100000
#        hard: 200000


  ## MongoDB for account metadata
  mongo_meta:
    image: mongo
    # feel free to change hard-coded memory limits to match your hardware requirements
    command: mongod --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=32000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 20
    ports:
      - "127.0.0.1:27018:27017"
    volumes:
      - $mongo_meta_dir:/data/db:delegated
    ulimits:
      nproc: 65535
      nofile:
        soft: 100000
        hard: 200000

  ### MAIN DB ###

  ## Config Servers
  main_config0:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet main_configserver --bind_ip_all
    volumes:
      - ./mongo_scripts:/scripts
    networks:
      - mongo_main


  ## Shards
  main_shard0a:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet main_shard0 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=10000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 20
    volumes:
      - ./mongo_scripts:/scripts
      - $mongo_main_0:/data/db:delegated
    networks:
      - mongo_main

  main_shard1a:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet main_shard1 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=10000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 20
    volumes:
      - ./mongo_scripts:/scripts
      - $mongo_main_1:/data/db:delegated
    networks:
      - mongo_main

  main_shard2a:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet main_shard2 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=10000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 20
    volumes:
      - ./mongo_scripts:/scripts
      - $mongo_main_2:/data/db:delegated
    networks:
      - mongo_main

  main_shard3a:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet main_shard3 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=10000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 20
    volumes:
      - ./mongo_scripts:/scripts
      - $mongo_main_3:/data/db:delegated
    networks:
      - mongo_main


  ## Router
  main_router:
    image: mongo
    command: mongos --port 27017 --configdb main_configserver/main_config0:27017,main_config1:27017 --bind_ip_all
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongo_scripts:/scripts
    depends_on:
      - main_config0
      - main_shard0a
      - main_shard1a
      - main_shard2a
      - main_shard3a
    networks:
      - mongo_main

  ### METADATA DB ###


networks:
  mongo_main:
  mongo_meta: