version: '3'

services:

    main_router:
        image: mongo
        command: mongos --port 27017 --configdb main_configserver/main_config0:27017 --bind_ip_all
        ports:
            - "127.0.0.1:27000:27017"
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        depends_on:
            - main_config0
            - main_shard1a
            - main_shard2a
            - main_shard3a
            - main_shard4a
            - main_shard5a
            - main_shard6a
            - main_shard7a
            - main_shard8a
            - main_shard9a
            - main_shard10a
        networks:
            - mongo_main

    main_config0:
        image: mongo
        command: mongod --port 27017 --configsvr --replSet main_configserver --bind_ip_all
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/main/mongo_config_0:/data/configdb:delegated
        networks:
            - mongo_main

    meta_router:
        image: mongo
        command: mongos --port 27017 --configdb meta_configserver/meta_config0:27017 --bind_ip_all
        ports:
            - "127.0.0.1:27001:27017"
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        depends_on:
            - meta_config0
            - meta_shard1a
            - meta_shard2a
            - meta_shard3a
            - meta_shard4a
            - meta_shard5a
            - meta_shard6a
            - meta_shard7a
            - meta_shard8a
            - meta_shard9a
            - meta_shard10a
        networks:
            - mongo_meta

    meta_config0:
        image: mongo
        command: mongod --port 27017 --configsvr --replSet meta_configserver --bind_ip_all
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/meta/mongo_config_0:/data/configdb:delegated
        networks:
            - mongo_meta

    main_shard1a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet main_shard1 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/main/mongo_shard_1a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_main

    main_shard2a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet main_shard2 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/main/mongo_shard_2a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_main

    main_shard3a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet main_shard3 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/main/mongo_shard_3a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_main

    main_shard4a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet main_shard4 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/main/mongo_shard_4a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_main

    main_shard5a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet main_shard5 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/main/mongo_shard_5a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_main

    main_shard6a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet main_shard6 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/main/mongo_shard_6a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_main

    main_shard7a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet main_shard7 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/main/mongo_shard_7a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_main

    main_shard8a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet main_shard8 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/main/mongo_shard_8a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_main

    main_shard9a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet main_shard9 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/main/mongo_shard_9a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_main

    main_shard10a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet main_shard10 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/main/mongo_shard_10a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_main

    meta_shard1a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet meta_shard1 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/meta/mongo_shard_1a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_meta

    meta_shard2a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet meta_shard2 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/meta/mongo_shard_2a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_meta

    meta_shard3a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet meta_shard3 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/meta/mongo_shard_3a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_meta

    meta_shard4a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet meta_shard4 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/meta/mongo_shard_4a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_meta

    meta_shard5a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet meta_shard5 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/meta/mongo_shard_5a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_meta

    meta_shard6a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet meta_shard6 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/meta/mongo_shard_6a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_meta

    meta_shard7a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet meta_shard7 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/meta/mongo_shard_7a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_meta

    meta_shard8a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet meta_shard8 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/meta/mongo_shard_8a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_meta

    meta_shard9a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet meta_shard9 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/meta/mongo_shard_9a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_meta

    meta_shard10a:
        image: mongo
        command: mongod --port 27018 --shardsvr --replSet meta_shard10 --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=2000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 5
        volumes:
            - /tmp/credshed/mongo_scripts:/scripts
            - /tmp/credshed/db/meta/mongo_shard_10a:/data/db:delegated
        ulimits:
            nproc: 65535
            nofile:
                soft: 100000
                hard: 200000
        networks:
            - mongo_meta

networks:
    mongo_main:
    mongo_meta:
