version: '2'


services:

  ## Config Servers
  config0:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc --smallfiles --oplogSize 16 --bind_ip_all
    volumes:
      - ./mongo_scripts:/scripts
#    networks:
#      - mongo_sharded

  config1:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc --smallfiles --oplogSize 16 --bind_ip_all
    volumes:
      - ./mongo_scripts:/scripts
#    networks:
#      - mongo_sharded

  ## Shards
  shard0a:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard0 --noprealloc --smallfiles --oplogSize 16 --bind_ip_all
    volumes:
      - ./mongo_scripts:/scripts
      - $mongo_dir_0:/data/db:delegated
#    networks:
#      - mongo_sharded

  shard1a:
    image: mongo
    command: mongod --port 27018 --shardsvr --replSet shard1 --noprealloc --smallfiles --oplogSize 16 --bind_ip_all
    volumes:
      - ./mongo_scripts:/scripts
      - $mongo_dir_1:/data/db:delegated
#    networks:
#      - mongo_sharded


  ## Router
  router:
    image: mongo
    command: mongos --port 27017 --configdb configserver/config0:27017,config1:27017 --bind_ip_all
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongo_scripts:/scripts
    depends_on:
      - config0
      - config1
      - shard0a
      - shard1a
#    networks:
#      - mongo_sharded


  ## Redis
  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "$redis_dir:/data:delegated"
    entrypoint: redis-server --maxmemory 5000000000 --maxmemory-policy allkeys-random



#networks:
#  mongo_sharded: