version: '2'
services:

  ## Config Servers
  config0:
    image: mongo
    command: mongod --port 27017 --configsvr --replSet configserver --noprealloc --smallfiles --oplogSize 16
    volumes:
      - ./mongo_scripts:/scripts

  ## Shards
  shard0a:
    image: mongo
    command: mongod --port 27018 --wiredTigerDirectoryForIndexes --shardsvr --replSet shard0 --noprealloc --smallfiles --oplogSize 16 --setParameter maxIndexBuildMemoryUsageMegabytes=20000 --setParameter diagnosticDataCollectionEnabled=false
    volumes:
      - ./mongo_scripts:/scripts
      - $mongo_dir_0/db:/data/db:delegated
  shard1a:
    image: mongo
    command: mongod --port 27018 --wiredTigerDirectoryForIndexes --shardsvr --replSet shard1 --noprealloc --smallfiles --oplogSize 16 --setParameter maxIndexBuildMemoryUsageMegabytes=20000 --setParameter diagnosticDataCollectionEnabled=false
    volumes:
      - ./mongo_scripts:/scripts
      - $mongo_dir_1/db:/data/db:delegated

  ## Router
  router:
    image: mongo
    command: mongos --port 27017 --configdb configserver/config0:27017 --bind_ip_all
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./mongo_scripts:/scripts
    depends_on:
      - config0
      - shard0a
      - shard1a

  redis:
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - "$redis_dir:/data:delegated"
    entrypoint: redis-server --maxmemory 5000000000 --maxmemory-policy allkeys-random