version: '3'

services:

  ## MongoDB
  mongo:
    image: mongo
    command: mongod --bind_ip_all --setParameter maxIndexBuildMemoryUsageMegabytes=32000 --setParameter diagnosticDataCollectionEnabled=false --wiredTigerCacheSizeGB 150
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - $mongo_dir_0:/data/db:delegated